/**
 * Next's own type declarations, referenced explicitly.
 *
 * `next-env.d.ts` carries the same reference but is generated by `next dev` /
 * `next build` and is git-ignored, so it does not exist when CI runs
 * `npm run typecheck` on a fresh checkout. Without it, the CSS imports in
 * `pages/_app.tsx` and `pages/index.tsx` have no module declaration. Duplicate
 * triple-slash references are de-duplicated by TypeScript, so this stays
 * correct once the generated file appears.
 */
/// <reference types="next" />
/// <reference types="next/image-types/global" />

export {};
